name: Build and push to aws

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Build project
        run: dotnet restore; dotnet publish -o site;

      - name: create zip package
        run: cd site; zip ../site.zip *;

      - name: Deploy to aws EB
        uses: einaregilsson/beanstalk-deploy@v21
        with: 
          aws_access_key: ${{ secrets.AWS_ENCRYPT_ACESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ENCRYPT_SECRET_ACCESS_KEY }}
          application_name: caesar-cipher-api
          environment_name: Caesar-cipher-api-env
          version_label: ${{ github.run_id }}
          region: eu-north-1
          deployment_package: site.zip
